version: "3.8"

services:
  qs-site:
    image: ghcr.io/quackstack-ltd/quackstack.net:latest
    environment:
      NODE_ENV: production
      HOSTNAME: "0.0.0.0"
    networks:
      - shared_network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
      labels:
        - traefik.enable=true
        - traefik.swarm.network=shared_network

        # Router for the website
        - traefik.http.routers.qs-site.rule=Host(`site.quackstack.net`)
        - traefik.http.routers.qs-site.entrypoints=websecure
        - traefik.http.routers.qs-site.tls=true
        - traefik.http.routers.qs-site.tls.certresolver=myresolver

        # Internal port for the service
        - traefik.http.services.qs-site.loadbalancer.server.port=3000
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "set -e; \
           wget -q -T 10 -O /dev/null https://site.quackstack.net/ || exit 1"
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

networks:
  shared_network:
    external: true
