name: Deploy

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          cd quackstack
          npm install

      - name: Deploy Application
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd quackstack
          npm run deploy
